package com.example.database

import com.example.model.Student

object DefaultStudentData {
    val initialStudents = listOf(
        // Group 1
        Student(rollNumber = "124", name = "RIVANSHU BEHAL", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "125", name = "SAHEJVEER SINGH", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "126", name = "RAYAN CHANDEL", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "127", name = "SUNDRAM KUMAR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "128", name = "SURYA DEY", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "129", name = "SAHIL GUPTA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "130", name = "VARENYA MAHAJAN", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "131", name = "VENU GOPAL SHARMA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "132", name = "SAWNI", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "133", name = "NAVDEEP KAUR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "134", name = "NIRJALA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "135", name = "MOHIT SINGH", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "136", name = "RASHMITA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "137", name = "SUNAKSHI MEHTA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "138", name = "SUKHMANPREET KAUR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "139", name = "NAVREET KAUR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "140", name = "PALAK SHARMA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "141", name = "ROHIT KUMAR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "143", name = "SIYA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "144", name = "RUDRAKSH SHARMA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "145", name = "PAVITERPREET SINGH", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "146", name = "PRITIKA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "147", name = "YOGITA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "148", name = "MANPREET KUMAR DHIR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "150", name = "PRANAV JOSHI", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "151", name = "SAWAL PUSHKARNA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "152", name = "SHASHANK SHEKHAR SOLANKI", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "153", name = "NAVNEET KAUR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "154", name = "PRABHNOOR SINGH", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "155", name = "VAIBHAV MAHAJAN", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "156", name = "RIDHAMPREET SINGH ARORA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "157", name = "VISHAL CHOUDHARY", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "158", name = "TRIBHUVAN SINGH SENGAR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "159", name = "SUSHEN GUPTA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "160", name = "SIDARTH ATTRI", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "161", name = "MOHIT SALWAN", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "162", name = "SANCHI SHARMA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "163", name = "RUDRAKSH MEHRA", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "164", name = "UJWAL", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "165", name = "NIMISH SURI", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "167", name = "PRIYANSHI", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "169", name = "VINEET KUMAR", semester = "3", section = "B", group = "Group 1"),
        Student(rollNumber = "170", name = "TEJAL CHOPRA", semester = "3", section = "B", group = "Group 1"),

        // Group 2
        Student(rollNumber = "171", name = "SACHIN KUMAR BHAGAT", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "172", name = "RAVDEEP KAUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "173", name = "MEHAKDEEP KAUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "174", name = "SHAURYA THAKUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "175", name = "VISHESH KUMAR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "176", name = "NAVJIT KAPIL", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "177", name = "SHIVANG GUPTA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "178", name = "NAVYA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "179", name = "SHAGUN KAUR CHAHAL", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "180", name = "SUKHMANI", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "181", name = "ROOPANSHI SHARMA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "182", name = "SAKSHAM GUPTA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "183", name = "SUKHMANJEET SINGH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "184", name = "NITISH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "185", name = "SOURAV", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "186", name = "SIRTAJ SINGH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "187", name = "SAMAIRA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "188", name = "PRABHNOOR KAUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "189", name = "SUSHANK BALHOTRA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "190", name = "TANMYA MAHAJAN", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "191", name = "SAKSHAM RATHOR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "192", name = "PAVNEET SINGH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "193", name = "MEHAK GUPTA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "194", name = "MANTHAN SHARMA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "195", name = "MRIDULA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "196", name = "MITHILESHWAR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "197", name = "SHIVANSH SHUKLA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "198", name = "PRINCE KUMAR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "199", name = "MANJOT KAUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "200", name = "MEHAKPREET SINGH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "201", name = "MANJOT SINGH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "202", name = "NANDINI RATHORE", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "203", name = "MISHTHI", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "204", name = "SUNIDHI SOOD", semester = "3", section = "B", group = "Group 2"),

        // Additional Group 2 Students
        Student(rollNumber = "90", name = "JASLEEN KAUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "91", name = "JASMIN KAUR SANDHU", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "92", name = "ANMOLDEEP KAUR", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "93", name = "GURANGAD SINGH", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "94", name = "ABHI VERMA", semester = "3", section = "B", group = "Group 2"),
        Student(rollNumber = "95", name = "GURSIMRAN SINGH", semester = "3", section = "B", group = "Group 2")
    )
}
